POST http://localhost:3001/api/blogs
Content-Type: application/json


{
  "title": "Adding a note linked to root user",
  "author": "rootie",
  "url": "http://rootieandNote.com.co",
  "likes": 5043,
  "userId": "62081ef630a1c186acf28384"
}