POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVycm9vdCIsImlkIjoiNjIwODFmMDYzMGExYzE4NmFjZjI4Mzg3IiwiaWF0IjoxNjQ0NzEyOTcxfQ.N6azCKFqizp1wUNyho5RDRI4sO4YihlPOAgIqtpMxwE

{
  "title": "Trying with token extractor and Superroot",
  "author": "Kiskimoski",
  "url": "http://Superroteiro.com.co",
  "likes": 0
}